import { Colors } from "@/src/constants/Colors";
import { Typography } from "@/src/constants/Typography";
import { StyleSheet } from "react-native";

const PREVIEW_MAX_HEIGHT = 180;

export const styles = StyleSheet.create({
  container: {
    marginVertical: 8,
    width: "100%",
  },
  compactStack: {
    width: "100%",
  },
  metaInline: {
    marginTop: 8,
  },
  metaHidden: {
    marginTop: 0,
    height: 0,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.dark.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.dark.border,
    paddingHorizontal: 14,
    paddingVertical: 14,
    width: "100%",
    position: "relative",
  },

  scrollArea: { width: "100%" },
  scrollContent: { flexGrow: 1 },
  layeredInput: { position: "relative", width: "100%" },
  composedInput: { flex: 1, justifyContent: "flex-start" },
  highlightLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  highlightText: {
    ...Typography.body,
    color: Colors.dark.text,
    lineHeight: 22,
  },
  inputOverlay: {
    ...Typography.body,
    color: "transparent",
    lineHeight: 22,
    textAlignVertical: "top",
    flexGrow: 1,
    width: "100%",
    includeFontPadding: false,
    padding: 0,
  },
  placeholderText: {
    ...Typography.body,
    color: Colors.dark.muted,
    lineHeight: 20,
  },
  hlNormal: { color: Colors.dark.text },
  hlCommand: { color: Colors.dark.tint, fontWeight: "600" },
  hlCommandArg: { color: Colors.dark.icon },
  hlTag: { color: Colors.dark.success, fontWeight: "500" },
  expandButton: {
    position: "absolute",
    bottom: 12,
    right: 12,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.dark.surface,
    borderWidth: 1,
    borderColor: Colors.dark.border,
    alignItems: "center",
    justifyContent: "center",
  },
  expandIcon: {
    ...Typography.body,
    color: Colors.dark.tint,
    fontWeight: "600",
  },
  collapseButton: {
    position: "absolute",
    right: 16,
    top: 4,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.dark.surface,
    borderWidth: 1,
    borderColor: Colors.dark.border,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  submitButton: {
    marginLeft: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.dark.tint,
    alignItems: "center",
    justifyContent: "center",
  },
  submitButtonDisabled: { backgroundColor: Colors.dark.muted },
  badgesContainer: {
    marginTop: 12,
    borderTopWidth: 1,
    borderColor: Colors.dark.border,
    paddingTop: 12,
  },
  badgesScroll: {
    width: "100%",
    maxHeight: PREVIEW_MAX_HEIGHT,
  },
  badgesContent: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingBottom: 4,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    marginRight: 8,
    marginBottom: 8,
    backgroundColor: Colors.dark.surface,
  },
  badgeIcon: {
    marginRight: 6,
  },
  badgeLabel: {
    ...Typography.caption,
    fontWeight: "600",
  },
  badgesPlaceholder: {
    height: 12,
  },
  commandPalette: {
    marginTop: 6,
    backgroundColor: Colors.dark.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.dark.border,
    overflow: "hidden",
  },
  commandScroll: { maxHeight: 220, width: "100%" },
  commandScrollContent: { flexGrow: 1 },
  commandItem: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.dark.border,
  },
  commandName: {
    ...Typography.body,
    color: Colors.dark.tint,
    fontWeight: "600",
  },
  commandDesc: {
    ...Typography.caption,
    color: Colors.dark.muted,
    marginTop: 2,
  },
});
